"""
Fetch the NEST brand fonts once and embed them in the repo.

A branded document that loads fonts over the network is a document that
renders differently depending on where it is opened. Printing to PDF proved
it: headless Chromium never fetched the webfonts, so every heading silently
fell back to Georgia and the PDF was not NEST-branded at all -- while the same
HTML looked correct in a browser, which is why it went unnoticed.

This downloads the latin subset of each weight actually used and writes
backend/../assets/brand_fonts.py, a module holding base64 woff2 and ready-made
@font-face rules. nest_brand.py inlines those, so a branded document is
self-contained: no network, no CDN, no difference between screen and print.

    python scripts/fetch_brand_fonts.py

Re-run only when a font or weight changes. The output is committed.
"""
from __future__ import annotations

import base64
import pathlib
import re
import sys
import urllib.request

REPO = pathlib.Path(__file__).resolve().parents[1]
OUT = REPO / "assets" / "brand_fonts.py"

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

# Families and the weights the brand CSS actually references. Keep the
# family= parameters ALPHABETICAL -- the css2 endpoint returns 400 otherwise.
CSS_URL = ("https://fonts.googleapis.com/css2?"
           "family=Cormorant+Garamond:wght@300;400;600&"
           "family=IBM+Plex+Mono:wght@400;500&"
           "family=Space+Grotesk:wght@300;400;500;600&display=swap")

# The latin block is the last unicode-range Google emits per weight and the
# only one these documents need. Matching on it keeps the payload ~10x smaller
# than taking every subset.
LATIN = "U+0000-00FF"


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def main() -> int:
    print(f"fetching {CSS_URL[:60]}...")
    css = get(CSS_URL).decode("utf-8")

    blocks = re.findall(r"@font-face\s*\{(.*?)\}", css, re.S)
    print(f"  {len(blocks)} @font-face blocks")

    faces: list[str] = []
    seen: set[tuple[str, str]] = set()
    total = 0

    for b in blocks:
        if LATIN not in b:
            continue
        fam = re.search(r"font-family:\s*'([^']+)'", b)
        wgt = re.search(r"font-weight:\s*(\d+)", b)
        src = re.search(r"src:\s*url\(([^)]+)\)", b)
        if not (fam and wgt and src):
            continue
        key = (fam.group(1), wgt.group(1))
        if key in seen:
            continue
        seen.add(key)

        data = get(src.group(1))
        total += len(data)
        b64 = base64.b64encode(data).decode("ascii")
        print(f"  + {key[0]} {key[1]} — {len(data) // 1024} KB")

        faces.append(
            "@font-face{font-family:'%s';font-style:normal;font-weight:%s;"
            "font-display:block;"
            "src:url(data:font/woff2;base64,%s) format('woff2')}"
            % (key[0], key[1], b64))

    if not faces:
        print("no latin faces matched — the css2 response shape changed",
              file=sys.stderr)
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        '"""NEST brand fonts, embedded. Generated by '
        'scripts/fetch_brand_fonts.py -- do not hand-edit."""\n\n'
        "FONT_FACE_CSS = (\n" +
        "\n".join(f'    "{f}"' for f in faces) +
        "\n)\n",
        encoding="utf-8")

    print(f"\nwrote {OUT}")
    print(f"  {len(faces)} faces · {total // 1024} KB raw · "
          f"{OUT.stat().st_size // 1024} KB base64")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
