// NEST Academy — Full Question Bank + 4-Week Curriculum
// 80 questions covering Series 7, 52, 54, 28

export interface AcademyQuestion {
  id: number;
  exam: 'S7' | 'S52' | 'S54' | 'S28';
  topic: string;
  difficulty: 'basic' | 'intermediate' | 'advanced';
  q: string;
  options: string[];
  correct: number;
  explanation: string;
  nestContext: string;
  stepByStep: string[];
  formulaUsed?: string;
}

export const FULL_QUESTION_BANK: AcademyQuestion[] = [
  // ─── SERIES 52 — Municipal Securities Representative (20 questions) ───
  {
    id: 1, exam: 'S52', topic: 'Bond Types', difficulty: 'basic',
    q: 'Which type of municipal bond is secured solely by revenues from a specific project?',
    options: ['General Obligation bond', 'Revenue bond', 'Special assessment bond', 'Moral obligation bond'],
    correct: 1,
    explanation: 'Revenue bonds are backed exclusively by revenues from the financed project — tolls, hospital fees, CCRC occupancy income. No taxing power backs them.',
    nestContext: 'All NEST deals (Jacaranda Trace $231M, HBO2 $155M) are revenue bonds. DSCR stress testing is critical because there is no GO backstop — the project must cover its own debt service.',
    stepByStep: [
      '1. General Obligation = full faith + taxing power of the municipality',
      '2. Revenue bond = ONLY backed by project revenues (occupancy fees, tolls, etc.)',
      '3. If revenues drop, bondholders have no claim on property taxes',
      '4. This is why NEST requires DSCR > 1.5x — must cover debt service from operations',
    ],
    formulaUsed: 'DSCR = NOI / Annual Debt Service',
  },
  {
    id: 2, exam: 'S52', topic: 'TEFRA', difficulty: 'intermediate',
    q: 'TEFRA requires a public approval process for which bond type?',
    options: ['All GO bonds', 'Tax-exempt private activity bonds (PABs)', 'Taxable munis', 'Agency bonds'],
    correct: 1,
    explanation: 'TEFRA (Tax Equity and Fiscal Responsibility Act) mandates a public hearing plus governmental body approval for PABs seeking tax-exempt status. Missing it triggers full taxability.',
    nestContext: "HBO2's $155M bond is a §501(c)(3) PAB. TEFRA hearing was held 2024-11-14 in St. Petersburg. Bond counsel Squire Patton Boggs certified compliance before LGFC conduit packaging.",
    stepByStep: [
      '1. Private Activity Bonds (PABs) benefit private users but use government conduit',
      '2. To get tax-exempt status, TEFRA requires: public notice + hearing + governmental approval',
      '3. If any step is skipped, the IRS treats all interest as taxable — retroactively',
      '4. Volume cap also limits annual PAB issuance per state (~$110/capita)',
    ],
  },
  {
    id: 3, exam: 'S52', topic: 'Yield Math', difficulty: 'intermediate',
    q: 'A muni bond has a 5% coupon, par $1,000, priced at 102. What is the current yield?',
    options: ['4.90%', '5.00%', '5.10%', '4.78%'],
    correct: 0,
    explanation: 'Current yield = Annual coupon ÷ Market price = $50 ÷ $1,020 = 4.902%. Premium price always drives current yield below coupon rate.',
    nestContext: 'NEST targets 6.25–6.75% current yield at issue. As Jacaranda Trace seasons and occupancy stabilizes above 90%, credit improves → price rises → yield compresses. Early buyers capture capital gain.',
    stepByStep: [
      '1. Annual coupon = $1,000 × 5% = $50',
      '2. Market price = $1,000 × 102% = $1,020',
      '3. Current yield = $50 ÷ $1,020 = 0.04902 = 4.90%',
      '4. Rule: bond at premium → current yield < coupon rate',
    ],
    formulaUsed: 'Current Yield = Annual Coupon / Market Price',
  },
  {
    id: 4, exam: 'S52', topic: 'Tax Equivalency', difficulty: 'intermediate',
    q: 'An investor in the 35% tax bracket evaluates a 4% muni bond. What taxable yield is equivalent?',
    options: ['4.00%', '5.40%', '6.15%', '5.71%'],
    correct: 2,
    explanation: 'TEY = Muni yield ÷ (1 − tax rate) = 4% ÷ 0.65 = 6.15%. An investor needs a 6.15% taxable bond to equal the after-tax return of the 4% muni.',
    nestContext: 'NEST institutional clients are often pension funds (tax-exempt) or family offices (high bracket). For a 37% bracket buyer, a 5% NEST muni = 7.94% taxable equivalent — material advantage over IG corporates.',
    stepByStep: [
      '1. TEY = Muni Rate / (1 - Marginal Tax Rate)',
      '2. TEY = 4% / (1 - 0.35)',
      '3. TEY = 4% / 0.65',
      '4. TEY = 6.154% → rounds to 6.15%',
    ],
    formulaUsed: 'TEY = Muni Yield / (1 − Tax Rate)',
  },
  {
    id: 5, exam: 'S52', topic: 'MSRB Rules', difficulty: 'basic',
    q: 'Under MSRB Rule G-17, a dealer is required to:',
    options: ['Always match the lowest competing quote', 'Deal fairly and not engage in deceptive practices', 'File pre-trade reports with FINRA', 'Obtain 3 competing bids before executing'],
    correct: 1,
    explanation: 'G-17 is the bedrock fair dealing rule: no deceptive, dishonest, or unfair practices. Requires disclosure of all material facts affecting the security.',
    nestContext: 'NEST bonds are placed with QIBs under Rule 144A. G-17 applies to any MSRB-registered dealer in the placement chain. Non-disclosure of surety risk or TEFRA status could void the offering.',
    stepByStep: [
      '1. G-17 = "Fair Dealing Rule" — the foundational MSRB rule',
      '2. Prohibits: deception, dishonesty, and unfair practices',
      '3. Requires: disclosure of material information affecting the bond',
      '4. Applies to: all MSRB-registered dealers, all transactions',
    ],
  },
  {
    id: 6, exam: 'S52', topic: 'Settlement', difficulty: 'basic',
    q: 'Standard settlement for municipal securities is:',
    options: ['T+0', 'T+1', 'T+2', 'T+3'],
    correct: 2,
    explanation: 'Municipal securities settle T+2 — two business days after trade date. Consistent with most equity and debt securities since the SEC\'s 2017 T+2 rule adoption.',
    nestContext: 'NEST bond desk tracks settlement on all placements. A $155M fail-to-deliver on HBO2 creates catastrophic counterparty exposure — Bridge Agent monitors DTC settlement daily.',
    stepByStep: ['1. Trade Date = T', '2. Settlement = T + 2 business days', '3. Counterparty delivers securities; buyer delivers funds', '4. Failure to settle = "fail" — triggers close-out procedures'],
  },
  {
    id: 7, exam: 'S52', topic: 'Official Statement', difficulty: 'intermediate',
    q: 'The official statement for a new muni issue must be delivered:',
    options: ['30 days before pricing', 'Before or with trade confirmation', 'Within 5 business days of settlement', 'Only upon investor request'],
    correct: 1,
    explanation: 'MSRB Rule G-32 requires dealers to deliver the OS to investors before or with trade confirmation for new issues. The OS is the primary disclosure document.',
    nestContext: 'Jacaranda Trace\'s OS includes 10-year proforma, occupancy projections, DSCR sensitivity analysis, and Hylant surety details. Bond counsel certifies OS accuracy before pricing.',
    stepByStep: ['1. OS = Official Statement = disclosure document for new muni issues', '2. G-32 mandates delivery before OR concurrent with confirmation', '3. Preliminary OS (POS) used before final pricing', '4. Final OS must be filed with EMMA after closing'],
  },
  {
    id: 8, exam: 'S52', topic: 'Credit Analysis', difficulty: 'advanced',
    q: 'A CCRC revenue bond has NOI of $12.5M and annual debt service of $8.2M. What is the DSCR and indicative rating?',
    options: ['1.52x — BBB-', '1.52x — BBB+', '1.32x — Sub-IG', '1.52x — A'],
    correct: 0,
    explanation: 'DSCR = $12.5M / $8.2M = 1.524x. Per JP Morgan benchmarks, DSCR 1.5-1.75 = BBB- (barely investment grade). Hylant surety or LC enhancement can lift to BBB+.',
    nestContext: 'Jacaranda Trace PLOM underwrites at 1.62x DSCR (95% occupancy stabilized). Maxwell Agent (credit underwriting) calculates DSCR across 5 stress scenarios including 80% occupancy floor.',
    stepByStep: [
      '1. DSCR = NOI / Debt Service = $12.5M / $8.2M = 1.524x',
      '2. JP Morgan benchmarks: A > 2.0x, BBB+ > 1.75x, BBB- > 1.5x, Sub-IG < 1.5x',
      '3. 1.524x sits just above 1.5x threshold → BBB- (lowest IG)',
      '4. With Hylant surety wrap → credit enhancement can push to BBB+',
    ],
    formulaUsed: 'DSCR = NOI / Annual Debt Service',
  },
  {
    id: 9, exam: 'S52', topic: 'Bond Insurance', difficulty: 'intermediate',
    q: 'Which entity provides the "full faith and credit" enhancement in a surety-wrapped muni bond?',
    options: ['The issuing municipality', 'The conduit issuer (LGFC)', 'The surety company (e.g. Hylant)', 'The bond trustee (US Bank)'],
    correct: 2,
    explanation: 'A surety company (insurer) wraps the bond — if the issuer defaults, the surety pays principal + interest. This external credit support lifts the bond\'s effective rating to the surety\'s rating.',
    nestContext: 'NEST uses Hylant Insurance for surety. Hylant\'s A-rated paper wraps NEST bonds at the AUM-based pricing tiers: $0-15M AUM = 0.85% premium, $80M+ AUM = 0.15% (self-collateralized).',
    stepByStep: ['1. Surety = insurance policy backing bond payments', '2. If issuer defaults, surety company pays principal + interest', '3. Bond effective rating = surety company\'s rating (not issuer)', '4. Premium: Hylant charges 0.15–0.85% of face depending on AUM tier'],
  },
  {
    id: 10, exam: 'S52', topic: 'Competitive vs Negotiated', difficulty: 'intermediate',
    q: 'In a negotiated underwriting, the underwriter is selected:',
    options: ['Via sealed competitive bid to the lowest spread', 'Before pricing through direct negotiation with the issuer', 'By FINRA lottery system', 'Only after 3 bids are received'],
    correct: 1,
    explanation: 'Negotiated offerings: underwriter selected in advance, works with issuer to structure and price. Competitive: sealed bids, lowest TIC wins. Most complex revenue bonds use negotiated — more structuring flexibility.',
    nestContext: 'NEST bond desk operates as negotiated underwriter/arranger. Complexity of CCRC revenue bonds (surety, TEFRA, conduit) requires upfront structuring collaboration — competitive bid would be impossible.',
    stepByStep: ['1. Competitive: sealed bids, award to lowest TIC/NIC', '2. Negotiated: underwriter selected first, then structures deal', '3. Complex bonds (revenue, conduit, derivatives) use negotiated', '4. NEST operates exclusively in negotiated space due to deal complexity'],
  },
  {
    id: 11, exam: 'S52', topic: 'Continuing Disclosure', difficulty: 'intermediate',
    q: 'SEC Rule 15c2-12 requires issuers to file annual continuing disclosure reports with:',
    options: ['FINRA', 'EMMA (MSRB)', 'SEC EDGAR', 'The bond trustee'],
    correct: 1,
    explanation: 'EMMA (Electronic Municipal Market Access) is the MSRB\'s disclosure repository. Issuers must file annual financial information and material event notices with EMMA under 15c2-12.',
    nestContext: 'Jacaranda Trace must file annual audited financials with EMMA. Bridge Agent (NEST) monitors EMMA for covenant compliance — revenue shortfalls must be disclosed as material events within 10 business days.',
    stepByStep: ['1. 15c2-12 requires continuing disclosure agreement (CDA)', '2. Annual report: audited financials + updated DSCR', '3. Material events (rating changes, defaults, draws on reserves) within 10 days', '4. All filings to EMMA — public access, free'],
  },
  {
    id: 12, exam: 'S52', topic: 'Political Contributions', difficulty: 'basic',
    q: 'MSRB Rule G-37 prohibits a dealer from engaging in muni securities business with an issuer for how long after a banned political contribution?',
    options: ['6 months', '1 year', '2 years', '4 years'],
    correct: 2,
    explanation: 'G-37 bans muni securities business for 2 years after a covered political contribution to an official of the issuer. De minimis exception: $250/election for candidates you can vote for.',
    nestContext: 'Pay-to-play is career-ending in munis. NEST maintains a contribution log for all employees. Any contribution over $250 to a LGFC/conduit official triggers automatic 2-year exclusion from that jurisdiction.',
    stepByStep: ['1. G-37 = "Pay to play" rule', '2. Contribution to issuer official → 2-year ban on business with that issuer', '3. De minimis: $250/election for candidates in your voting district', '4. Includes contributions from municipal finance professionals (MFPs)'],
  },
  {
    id: 13, exam: 'S52', topic: 'Volume Cap', difficulty: 'advanced',
    q: 'Annual state volume cap for private activity bonds (PABs) is approximately:',
    options: ['$50 per capita', '$85 per capita', '$110 per capita', '$200 per capita'],
    correct: 2,
    explanation: 'The federal PAB volume cap is $110 per capita (indexed for inflation) or $331.8M minimum per state, whichever is greater. States allocate this among competing bond projects.',
    nestContext: 'HBO2\'s $155M is a §501(c)(3) exempt facility bond — NOT subject to volume cap. But NEST\'s other conduit deals (non-501c3) compete for Florida\'s annual volume cap allocation. Atlas Agent tracks remaining cap by state.',
    stepByStep: ['1. Volume cap limits tax-exempt PAB issuance per state per year', '2. Cap = greater of $110/capita OR $331.8M minimum', '3. 501(c)(3) bonds (hospitals, nonprofits) are cap-exempt', '4. States can carry forward unused cap 3 years (carryforward elections)'],
  },
  {
    id: 14, exam: 'S52', topic: 'MSRB G-30', difficulty: 'intermediate',
    q: 'MSRB Rule G-30 governs:',
    options: ['Political contributions', 'Customer protection rule', 'Prices and commissions', 'Continuing education'],
    correct: 2,
    explanation: 'G-30 requires dealers to purchase/sell at fair and reasonable prices, considering current market conditions. Markups/markdowns must be fair — typically compared to dealer\'s contemporaneous cost.',
    nestContext: 'When NEST secondary trades occur in seasoned bonds, G-30 applies. A dealer marking up a $100 NEST bond by 3 points ($3) must justify that spread based on market conditions — excessive markups are enforcement targets.',
    stepByStep: ['1. G-30 = fair pricing rule for customer transactions', '2. Price must be "fair and reasonable" given current market', '3. Benchmark: dealer\'s contemporaneous cost (interdealer price)', '4. MSRB enforcement looks at markups > 2-3% as presumptively unfair'],
  },
  {
    id: 15, exam: 'S52', topic: 'Moral Obligation Bond', difficulty: 'advanced',
    q: 'A "moral obligation" pledge in a muni bond means:',
    options: ['The issuer is legally required to appropriate funds', 'The legislature may (but is not required to) appropriate funds to replenish reserves', 'The surety company is required to pay', 'The federal government backstops the bond'],
    correct: 1,
    explanation: 'Moral obligation = non-binding commitment by legislature to replenish debt service reserves if drawn. Not a legal obligation — legislature can choose not to appropriate. Provides political (not legal) comfort.',
    nestContext: 'NEST avoids moral obligation structures — investors and Hylant require harder credit support. Direct surety wrap or LC are preferred over moral obligation for BBB+ targeting.',
    stepByStep: ['1. Moral obligation ≠ legal obligation', '2. If debt service reserve is drawn, legislature is "expected" to replenish', '3. Legislature can refuse — no bondholder recourse', '4. Risk: if legislature is hostile, moral obligation is worthless paper'],
  },
  {
    id: 16, exam: 'S52', topic: 'Revenue Bond Pledge', difficulty: 'intermediate',
    q: 'In a gross revenue pledge, debt service is paid from:',
    options: ['Net revenues after operating expenses', 'All revenues before operating expenses', 'Only reserve fund earnings', 'Tax increment revenues only'],
    correct: 1,
    explanation: 'Gross pledge = debt service paid from ALL revenues before expenses. Net pledge = revenues minus operating expenses first. Gross pledge is stronger for bondholders but rare — most CCRC bonds use net pledge.',
    nestContext: 'Jacaranda Trace uses a net revenue pledge — operating expenses (staffing, food service, utilities) are paid first, then debt service. This is why robust NOI (not just gross revenue) is the key underwriting metric.',
    stepByStep: ['1. Gross pledge: revenue → debt service (expenses come after)', '2. Net pledge: revenue → expenses → debt service (weaker for bondholders)', '3. Most revenue bonds are net pledge', '4. NEST underwriting focuses on NOI because of net pledge structure'],
  },
  {
    id: 17, exam: 'S52', topic: 'Reserve Fund', difficulty: 'intermediate',
    q: 'A debt service reserve fund (DSRF) is typically sized at:',
    options: ['1 month of debt service', 'Maximum Annual Debt Service (MADS)', '10% of par value', '5% of annual revenues'],
    correct: 1,
    explanation: 'The DSRF is typically sized at MADS — the highest single year\'s debt service over the life of the bond. This provides a full year\'s cushion if revenues fail.',
    nestContext: 'NEST bonds include a 2.5% maturity reserve fund escrowed at closing. DSRF is funded from bond proceeds. Bridge Agent monitors the reserve fund balance quarterly — a draw triggers a material event EMMA filing.',
    stepByStep: ['1. DSRF = cushion if issuer misses a debt service payment', '2. Typically sized = Maximum Annual Debt Service (MADS)', '3. If drawn, issuer must replenish within 12-24 months per indenture', '4. Surety companies can also provide synthetic DSRF (LOC substitute)'],
  },
  {
    id: 18, exam: 'S52', topic: 'Conduit Issuer', difficulty: 'intermediate',
    q: 'In a conduit financing, which entity is primarily responsible for debt service?',
    options: ['The conduit issuer (e.g. LGFC)', 'The obligor/borrower (e.g. the CCRC operator)', 'The bond trustee', 'FINRA'],
    correct: 1,
    explanation: 'The conduit issuer (LGFC, housing authority, etc.) lends proceeds to the obligor/borrower. The OBLIGOR is responsible for debt service — the conduit issuer has no obligation to use its own funds.',
    nestContext: "Florida's LGFC is Jacaranda Trace's conduit issuer. LGFC issues the bonds, loans proceeds to Jacaranda, and Jacaranda makes all debt service payments. LGFC's credit is NOT pledged — only Jacaranda's revenues.",
    stepByStep: ['1. Conduit issuer: governmental body, issues bonds for tax-exempt status', '2. Proceeds loaned to private borrower (obligor)', '3. Obligor makes loan payments → trustee → bondholders', '4. Conduit issuer has NO payment obligation — look to obligor only'],
  },
  {
    id: 19, exam: 'S52', topic: 'Rating Agencies', difficulty: 'basic',
    q: 'Which rating designates the lowest investment-grade rating from Moody\'s?',
    options: ['Baa1', 'Baa2', 'Baa3', 'Ba1'],
    correct: 2,
    explanation: 'Moody\'s scale: Aaa (highest) → Baa3 (lowest IG) → Ba1 (first junk). Baa3 = BBB- on S&P scale. Below Baa3/Ba1 = "speculative grade" or "high yield."',
    nestContext: "NEST's Series A bonds target Baa2-Baa1 (BBB/BBB+) with Hylant surety. Series B targets Ba1-Ba2 (BB). NEST's shadow rating engine (Maxwell Agent) predicts Moody's grade before formal engagement.",
    stepByStep: ['1. Moody\'s IG: Aaa, Aa1, Aa2, Aa3, A1, A2, A3, Baa1, Baa2, Baa3', '2. Non-IG: Ba1, Ba2, Ba3, B1, B2, B3, Caa, Ca, C', '3. Baa3 = lowest IG (S&P equivalent: BBB-)', '4. Ba1 = first sub-IG (S&P equivalent: BB+)'],
  },
  {
    id: 20, exam: 'S52', topic: 'NRO', difficulty: 'advanced',
    q: 'A "non-rated obligation" (NRO) in a muni portfolio refers to:',
    options: ['A bond rated below Baa3', 'A bond with no rating from a major NRSRO', 'A federally taxable muni bond', 'A bond in default'],
    correct: 1,
    explanation: 'NRO = municipal bond not rated by Moody\'s, S&P, or Fitch. Common for small deals, conduit bonds, or issuers avoiding rating costs. Higher yield premium required; suitability scrutiny required for retail accounts.',
    nestContext: 'Small NEST deals ($25-50M) may launch as NROs to save $150-300k in rating agency fees. QIB buyers conduct their own due diligence. NEST shadow rating provides independent analysis to institutional buyers.',
    stepByStep: ['1. NRO: issued without NRSRO rating (Moody\'s, S&P, Fitch, Kroll)', '2. Common for small conduit deals where rating cost > benefit', '3. Institutional buyers (QIBs) can buy NROs — do own DD', '4. Retail buyers: suitability analysis required; many firms restrict NRO sales'],
  },

  // ─── SERIES 7 — General Securities Representative (20 questions) ───
  {
    id: 21, exam: 'S7', topic: 'Bond Pricing', difficulty: 'basic',
    q: 'A bond\'s coupon is 6%, par $1,000, priced at 105. What is the current yield?',
    options: ['5.71%', '6.00%', '6.30%', '5.50%'],
    correct: 0,
    explanation: 'Current yield = $60 / $1,050 = 5.714%. Premium bond (price > par) → current yield < coupon rate. The yield compresses because you\'re paying more than par for the same coupon.',
    nestContext: "If HBO2's $155M bond (6.25% coupon) trades at 101 in secondary market, current yield = 6.25% / 1.01 = 6.19%. NEST's bond desk monitors secondary spreads through Bloomberg BVAL.",
    stepByStep: ['1. Annual coupon = $1,000 × 6% = $60', '2. Market price = $1,000 × 1.05 = $1,050', '3. Current yield = $60 / $1,050 = 0.05714 = 5.71%', '4. Rule: premium bond → current yield < coupon'],
    formulaUsed: 'Current Yield = Annual Coupon / Market Price',
  },
  {
    id: 22, exam: 'S7', topic: 'YTM', difficulty: 'advanced',
    q: 'A bond with 6% coupon, par $1,000, 10 years to maturity, priced at $900. YTM is approximately:',
    options: ['6.67%', '7.22%', '6.00%', '8.00%'],
    correct: 1,
    explanation: 'YTM ≈ [Coupon + (Par-Price)/Years] / [(Par+Price)/2] = [$60 + $10] / $950 = 7.37%. Exact YTM = 7.22% via Newton-Raphson. Discount bond → YTM > coupon.',
    nestContext: 'NEST\'s finance-math.ts engine uses Newton-Raphson to solve exact YTM. For Jacaranda bonds, accurate YTM is critical for Quantum HFT fund\'s duration-matched hedge positions.',
    stepByStep: [
      '1. Approximation: YTM ≈ [Annual Coupon + (Par - Price) / Years] / [(Par + Price) / 2]',
      '2. = [$60 + ($1,000-$900)/10] / [($1,000+$900)/2]',
      '3. = [$60 + $10] / [$950] = $70 / $950 = 7.37% (approx)',
      '4. Exact via Newton-Raphson solver = 7.22%',
    ],
    formulaUsed: 'YTM ≈ [Coupon + (Par − Price)/n] / [(Par + Price)/2]',
  },
  {
    id: 23, exam: 'S7', topic: 'Duration', difficulty: 'advanced',
    q: 'If a bond has a modified duration of 7.5 and rates rise 50 bps, the price change is approximately:',
    options: ['-3.75%', '+3.75%', '-7.50%', '-0.75%'],
    correct: 0,
    explanation: '% price change ≈ −Modified Duration × Δy = −7.5 × 0.0050 = −0.0375 = −3.75%. Duration tells you: for every 1% rate move, price moves by Duration% in the opposite direction.',
    nestContext: 'Vector Agent monitors portfolio duration daily. NEST\'s 25-year Jacaranda bonds have high duration (~15). A 50 bps rate rise = ~7.5% price drop. Apex Agent hedges this with TLT puts.',
    stepByStep: [
      '1. Modified Duration = sensitivity of price to yield changes',
      '2. % ΔP ≈ −Modified Duration × Δy',
      '3. Δy = +50 bps = +0.0050',
      '4. % ΔP ≈ −7.5 × 0.0050 = −0.0375 = −3.75%',
    ],
    formulaUsed: '% ΔP ≈ −Modified Duration × Δy',
  },
  {
    id: 24, exam: 'S7', topic: 'Convexity', difficulty: 'advanced',
    q: 'Convexity in bond pricing means that as yields rise, the price decline is:',
    options: ['Greater than duration predicts', 'Exactly equal to duration prediction', 'Less than duration predicts', 'Unrelated to duration'],
    correct: 2,
    explanation: 'Convexity = the curve of the price/yield relationship. Duration is linear (first-order). Convexity adjusts for the fact that as yields rise, price falls LESS than duration predicts; as yields fall, price rises MORE.',
    nestContext: 'NEST bonds with surety wraps have higher convexity (callable structure). Positive convexity is favorable — investors get more upside than downside vs. their duration model. Atlas Agent prices convexity adjustments.',
    stepByStep: ['1. Duration = linear estimate of price change', '2. Actual price/yield curve is convex (curved), not straight', '3. When rates rise: actual price > duration-predicted price (less damage)', '4. When rates fall: actual price > duration-predicted price (more gain)'],
  },
  {
    id: 25, exam: 'S7', topic: 'Options', difficulty: 'basic',
    q: 'An investor buys 1 XYZ Jan 50 call at $3 premium. Maximum loss is:',
    options: ['$50', '$300', '$5,300', 'Unlimited'],
    correct: 1,
    explanation: 'Maximum loss for option buyer = premium paid = $3 × 100 shares = $300. The call expires worthless if XYZ stays below $50. That\'s all you lose.',
    nestContext: 'Vector Agent manages interest rate options (TLT puts) on NEST\'s bond desk. Same logic: maximum loss on a TLT put = the premium paid. Defined-risk hedging with no unlimited exposure.',
    stepByStep: ['1. Call buyer\'s max loss = premium paid', '2. Premium = $3/share × 100 shares/contract = $300', '3. If XYZ < $50 at expiration, call expires worthless', '4. Max loss = $300 regardless of how far below $50 XYZ falls'],
  },
  {
    id: 26, exam: 'S7', topic: 'Options', difficulty: 'intermediate',
    q: 'An investor writes 1 XYZ Jan 50 put at $4 premium. Maximum gain is:',
    options: ['Unlimited', '$4,600', '$400', '$4,000'],
    correct: 2,
    explanation: 'Short put: maximum gain = premium received = $4 × 100 = $400. If XYZ stays above $50, put expires worthless and the writer keeps the premium.',
    nestContext: 'Apex Agent sometimes sells puts on TLT to generate premium income when the rate outlook is stable. Max gain = premium. Max loss if TLT collapses = (strike - 0) × 100 − premium.',
    stepByStep: ['1. Short put (writer) receives premium upfront', '2. If XYZ > strike at expiration, put expires worthless', '3. Max gain = full premium = $4 × 100 = $400', '4. Max loss = strike × 100 − premium (if underlying goes to $0)'],
  },
  {
    id: 27, exam: 'S7', topic: 'Options', difficulty: 'intermediate',
    q: 'Breakeven for a long call with strike $60 and $4 premium is:',
    options: ['$56', '$60', '$64', '$4'],
    correct: 2,
    explanation: 'Call buyer BEP = Strike + Premium = $60 + $4 = $64. You need the stock to rise above $64 to profit — below that, you\'ve paid more in premium than the intrinsic value.',
    nestContext: 'When NEST structures equity kickers (warrants) on mezzanine debt, the warrant strike determines the breakeven. Hawkeye Sterling agent prices warrant coverage for mezz investors.',
    stepByStep: ['1. Long call BEP = Strike + Premium', '2. Strike = $60, Premium = $4', '3. BEP = $60 + $4 = $64', '4. Above $64: profit. Below $64: loss up to maximum loss of $400'],
    formulaUsed: 'Call BEP = Strike Price + Premium Paid',
  },
  {
    id: 28, exam: 'S7', topic: 'Options', difficulty: 'intermediate',
    q: 'A covered call consists of:',
    options: ['Long put + short stock', 'Long stock + short call', 'Short put + short stock', 'Long call + long put'],
    correct: 1,
    explanation: 'Covered call = long stock + short call on the same stock. Strategy: generate income from the call premium while holding the stock. Capped upside (call limits gains above strike).',
    nestContext: 'NEST\'s HFT Quantum fund uses covered calls on equity positions to generate alpha. If a position is flat, writing calls generates income. Vector Agent optimizes strike selection based on IV surface.',
    stepByStep: ['1. "Covered" = the short call is covered by owning the underlying stock', '2. Long 100 shares + short 1 call option', '3. Purpose: generate premium income', '4. Risk: if stock soars, gain is capped at strike + premium'],
  },
  {
    id: 29, exam: 'S7', topic: 'Mutual Funds', difficulty: 'basic',
    q: 'An investor redeems mutual fund shares at 2pm. The price received is:',
    options: ['The 2pm price', 'The next NAV calculated after 4pm close', 'Yesterday\'s NAV', 'The bid price at 2pm'],
    correct: 1,
    explanation: 'Forward pricing rule: mutual fund orders submitted any time during the day receive the NEXT calculated NAV (typically 4:00 PM ET). No intraday trading of open-end funds.',
    nestContext: 'NEST institutional clients prefer ETFs for this reason — trade at market price intraday, allowing real-time hedging against bond desk activity. Mutual funds have 24-hour pricing lag.',
    stepByStep: ['1. Open-end funds price once daily at 4:00 PM ET (NAV)', '2. Any order received before 4pm gets same-day close NAV', '3. Any order after 4pm gets NEXT business day NAV', '4. No intraday trading — always forward priced'],
  },
  {
    id: 30, exam: 'S7', topic: 'Margin', difficulty: 'intermediate',
    q: 'Regulation T initial margin requirement for equity securities is:',
    options: ['25%', '50%', '75%', '100%'],
    correct: 1,
    explanation: 'Reg T (Federal Reserve) requires 50% initial margin for long equity positions. You must deposit 50% of the purchase price; the broker lends the other 50%.',
    nestContext: 'NEST\'s Quantum HFT fund uses margin in its equity sleeve. 50% Reg T initial margin means $1M buys $2M of equities. Maintenance margin (25% FINRA minimum) = margin call if account drops below that level.',
    stepByStep: ['1. Reg T = Federal Reserve regulation on margin lending', '2. Initial requirement: 50% — investor provides half the cost', '3. Broker lends remaining 50% (margin loan)', '4. Maintenance minimum: 25% (FINRA) — below triggers margin call'],
    formulaUsed: 'Initial Margin = 50% × Purchase Price',
  },
  {
    id: 31, exam: 'S7', topic: 'Corporate Bonds', difficulty: 'intermediate',
    q: 'A zero-coupon bond is purchased at $600 and matures at $1,000 in 8 years. Annual accretion is taxed as:',
    options: ['Capital gain only at maturity', 'Ordinary income each year (phantom income)', 'Tax-exempt income', 'Not taxed until sold'],
    correct: 1,
    explanation: 'Zero-coupon bond OID (original issue discount) must be accreted annually and taxed as ordinary income each year — even though no cash is received. This is "phantom income."',
    nestContext: 'NEST structures zero-coupon IO periods on some deals to maximize early cash flow for construction draws. Institutional investors in tax-advantaged accounts (pension, IRA) prefer zeros to avoid phantom income issues.',
    stepByStep: ['1. Zero-coupon bond: no cash payments, bought at deep discount', '2. Discount = OID (original issue discount)', '3. OID must be accreted to par over life of bond', '4. Each year\'s accretion = taxable ordinary income (even with no cash received)'],
  },
  {
    id: 32, exam: 'S7', topic: 'Market Mechanics', difficulty: 'basic',
    q: 'A "market order" guarantees:',
    options: ['Execution at the best available price', 'Execution at a specific price', 'No execution if price moves', 'Execution only on exchange'],
    correct: 0,
    explanation: 'Market orders execute immediately at the best available price. They guarantee execution but NOT a specific price. In fast markets, you may get a significantly different price than expected.',
    nestContext: 'NEST bond desk uses limit orders for large block trades — a $50M market order in a thin muni market could move the price 2-3 points. Hawkeye agent only executes with limit or VWAP algos.',
    stepByStep: ['1. Market order = execute NOW at whatever price is available', '2. Guarantees execution', '3. Does NOT guarantee a specific price', '4. Suitable for liquid securities only — thin markets = wide slippage'],
  },
  {
    id: 33, exam: 'S7', topic: 'Convertible Bonds', difficulty: 'intermediate',
    q: 'A convertible bond with $1,000 par converts to 25 shares. Current stock price is $48. Parity price of the bond is:',
    options: ['$1,000', '$1,200', '$48', '$1,050'],
    correct: 1,
    explanation: 'Parity = shares × stock price = 25 × $48 = $1,200. The bond is worth at least $1,200 at parity. If the bond trades below $1,200, arbitrage opportunity exists.',
    nestContext: 'NEST structures convertible notes for Celebrity Crush (seed stage). A $500k convert at 25% discount to Series A means early money gets equity at lower valuation. Conversion parity drives the hedge ratio.',
    stepByStep: ['1. Conversion ratio = $1,000 / conversion price', '2. Number of shares upon conversion = 25 shares', '3. Parity value = shares × current stock price', '4. Parity = 25 × $48 = $1,200'],
    formulaUsed: 'Parity = Conversion Ratio × Current Stock Price',
  },
  {
    id: 34, exam: 'S7', topic: 'Preferred Stock', difficulty: 'basic',
    q: 'Which of the following is NOT a characteristic of preferred stock?',
    options: ['Fixed dividend priority over common', 'Voting rights in most circumstances', 'Cumulative dividend provision', 'No participation in unlimited capital appreciation'],
    correct: 1,
    explanation: 'Preferred stock typically has NO voting rights (unlike common stock). It has dividend priority, may have cumulative provisions, and limited capital appreciation (capped at par or call price).',
    nestContext: 'NEST\'s HFT fund holds preferred positions in structured vehicles. Fixed-yield + no voting = ideal for institutional architecture where control stays with the sponsor.',
    stepByStep: ['1. Preferred: fixed dividend, paid before common', '2. Cumulative preferred: missed dividends accumulate, paid before common gets anything', '3. Preferred: typically NO voting rights', '4. Capital appreciation: capped at par or call price (unlike common)'],
  },
  {
    id: 35, exam: 'S7', topic: 'Short Sales', difficulty: 'intermediate',
    q: 'The alternative uptick rule (Rule 201) restricts short selling when a stock has declined:',
    options: ['More than 5% intraday', 'More than 10% from the previous close', 'Any amount', 'More than 2% from the previous close'],
    correct: 1,
    explanation: 'Rule 201 (alternative uptick rule): triggered when stock price falls 10%+ from previous day\'s close. Restricts short sales to uptick prices for remainder of that day and next day.',
    nestContext: 'Apex Agent monitors circuit breakers. When TLT drops 10%+ (rates spike), Rule 201 restricts short sales. Apex pivots to put options as the hedging instrument — same economic effect, no uptick restriction.',
    stepByStep: ['1. Rule 201 = Alternative Uptick Rule (adopted 2010)', '2. Trigger: stock falls 10%+ from previous close', '3. Effect: short sales only permitted at price > best bid (uptick)', '4. Duration: triggered day + next trading day'],
  },
  {
    id: 36, exam: 'S7', topic: 'New Issues', difficulty: 'intermediate',
    q: 'In an IPO, which party bears the underwriting risk in a "firm commitment" offering?',
    options: ['The issuer', 'The underwriter', 'FINRA', 'The investors'],
    correct: 1,
    explanation: 'Firm commitment: underwriter buys ALL shares from issuer at a set price and resells to public. Underwriter bears ALL market risk — if the deal breaks, the underwriter holds unsold shares at a loss.',
    nestContext: 'NEST operates as arranger/placement agent (not firm commitment underwriter) for bond deals. This limits NEST\'s market risk — we place bonds with investors but don\'t hold unsold inventory.',
    stepByStep: ['1. Firm commitment: underwriter purchases 100% of shares from issuer', '2. Underwriter resells to public at offering price', '3. If market turns, underwriter holds unsold shares at loss', '4. Alternative: best efforts (no guarantee) or standby commitment'],
  },
  {
    id: 37, exam: 'S7', topic: 'Registration', difficulty: 'basic',
    q: 'Under the Securities Act of 1933, a security exempt from registration includes:',
    options: ['NYSE-listed stocks', 'Treasury securities', 'Corporate bonds over $5M', 'All preferred stock'],
    correct: 1,
    explanation: 'Government securities (Treasury, agency) are exempt from Securities Act 1933 registration. Also exempt: muni bonds, intrastate offerings (Rule 147), private placements (Reg D), commercial paper under 270 days.',
    nestContext: 'NEST bonds use Rule 144A private placement exemption — sold only to QIBs, no registration required. This saves $500k+ in SEC registration costs and 6-12 months of review time.',
    stepByStep: ['1. 1933 Act: requires registration for public offerings', '2. Exemptions: government securities, munis, Rule 144A (QIBs), Reg D, intrastate', '3. Treasury bonds are always exempt — full faith & credit of US govt', '4. NEST uses 144A exemption for institutional-only bond placements'],
  },
  {
    id: 38, exam: 'S7', topic: 'Options Strategies', difficulty: 'advanced',
    q: 'A long straddle involves:',
    options: ['Long call + long put at different strikes', 'Long call + long put at the SAME strike', 'Short call + short put', 'Long stock + long put'],
    correct: 1,
    explanation: 'Long straddle: buy call AND put at same strike + same expiration. Profits from large price moves in either direction. Best when you expect volatility but uncertain about direction.',
    nestContext: 'Before major FOMC decisions, uncertainty about rate direction is high. Vector Agent models straddle payoffs on TLT — if rates move 50+ bps either way, straddle profits. Neutral on direction, long volatility.',
    stepByStep: ['1. Long straddle = long call + long put at same strike, same expiry', '2. Pay two premiums (expensive)', '3. Need stock to move significantly in either direction to profit', '4. Maximum loss = combined premium (if stock stays exactly at strike)'],
  },
  {
    id: 39, exam: 'S7', topic: 'Types of Orders', difficulty: 'basic',
    q: 'A "stop-limit" order to sell at $45 stop, $43 limit means:',
    options: ['Sell at exactly $45', 'When price hits $45, becomes a limit order to sell at $43 or better', 'Sell between $43 and $45 only', 'Cancel order if price drops below $43'],
    correct: 1,
    explanation: 'Stop-limit: when price hits the stop ($45), it triggers a limit order at $43. It will only execute at $43 or higher. Risk: if market gaps down past $43, order does NOT execute.',
    nestContext: 'NEST bond desk uses stop-limit orders in the HFT equity sleeve. In a fast-moving market, a plain stop order can fill at a terrible price. Stop-limit gives price control but risks non-execution.',
    stepByStep: ['1. Stop price ($45): triggers the order when hit', '2. Once triggered, becomes a LIMIT order at $43', '3. Will only execute at $43 or better', '4. Risk: if price gaps from $46 to $42, order triggers but never fills'],
  },
  {
    id: 40, exam: 'S7', topic: 'Suitability', difficulty: 'intermediate',
    q: 'Under FINRA Rule 2111, suitability requires that recommended securities be appropriate based on:',
    options: ['Commission generated only', 'Customer\'s investment profile including objectives, time horizon, and risk tolerance', 'The security\'s rating only', 'Market conditions at time of recommendation'],
    correct: 1,
    explanation: 'FINRA 2111 suitability: recommendations must be based on reasonable diligence about the customer\'s profile — financial situation, investment objectives, time horizon, liquidity needs, risk tolerance, and other investments.',
    nestContext: 'NEST bonds ($25M minimum) are limited to QIBs. Even QIBs have suitability profiles. A pension fund with 7-year liability matching needs different duration bonds than a university endowment with 30-year horizon.',
    stepByStep: ['1. FINRA 2111 requires "reasonable basis" suitability', '2. Must know the customer: financial situation, objectives, time horizon', '3. Must know the product: risks, rewards, costs, liquidity', '4. Match product to customer — document your analysis'],
  },

  // ─── SERIES 54 — Municipal Advisor Representative (20 questions) ───
  {
    id: 41, exam: 'S54', topic: 'MA Registration', difficulty: 'basic',
    q: 'Who must register as a municipal advisor under Dodd-Frank?',
    options: ['All broker-dealers', 'Persons who provide advice to municipal entities regarding municipal securities', 'Only underwriters', 'Any person who sells bonds'],
    correct: 1,
    explanation: 'Dodd-Frank created the municipal advisor (MA) category: persons providing advice to municipal entities or obligated persons about issuance of municipal securities, or about investment of bond proceeds.',
    nestContext: 'NEST operates as placement agent/arranger — NOT as a municipal advisor. This distinction is critical. Acting as MA without registration violates Dodd-Frank and triggers enforcement. Atticus agent monitors regulatory status.',
    stepByStep: ['1. MA defined: gives advice to muni entity about issuance or investments', '2. Must register with SEC (Form MA) and MSRB', '3. Subject to fiduciary duty to the municipal entity client', '4. Underwriters are excluded — they serve the offering, not the issuer'],
  },
  {
    id: 42, exam: 'S54', topic: 'Fiduciary Duty', difficulty: 'intermediate',
    q: 'A municipal advisor\'s fiduciary duty means:',
    options: ['Duty to maximize fee income', 'Duty to act in the best interest of the municipal entity client', 'Duty to disclose all bond information to investors', 'Duty to recommend only rated securities'],
    correct: 1,
    explanation: 'MAs owe a fiduciary duty to their municipal entity clients — a legal obligation to act in the client\'s best interest, ahead of the MA\'s own interests. This is higher than suitability (FINRA 2111).',
    nestContext: 'NEST as arranger does NOT owe fiduciary duty to the borrower — we represent our own principal interest. Municipal advisors representing Jacaranda Trace MUST disclose conflicts and act solely in Jacaranda\'s interest.',
    stepByStep: ['1. Fiduciary > suitability: must act in CLIENT\'s best interest, not just "suitable"', '2. Must disclose all conflicts of interest', '3. Cannot engage in transactions that benefit MA at client\'s expense', '4. Applies to: advice about issuance AND investment of proceeds'],
  },
  {
    id: 43, exam: 'S54', topic: 'G-42', difficulty: 'advanced',
    q: 'MSRB Rule G-42 requires a municipal advisor to:',
    options: ['File all opinions with FINRA', 'Disclose conflicts and act in the best interest of the municipal entity', 'Obtain 3 competing proposals', 'Register with the SEC only'],
    correct: 1,
    explanation: 'G-42 codifies the core duties for non-solicitor MAs: duty of care, duty of loyalty (best interest), and disclosure obligations. The rule requires written disclosure of conflicts and prohibits undisclosed compensation.',
    nestContext: 'If NEST ever takes on a formal MA role, G-42 compliance is mandatory. Written engagement letter, conflict disclosure, best interest standard — all required before giving advice. Atticus Agent drafts G-42 compliance memos.',
    stepByStep: ['1. G-42 = MSRB\'s rule codifying MA duties', '2. Duty of care: must have reasonable basis for advice', '3. Duty of loyalty: client\'s best interest above MA\'s', '4. Disclosure: all conflicts must be disclosed in writing before engagement'],
  },
  {
    id: 44, exam: 'S54', topic: 'Solicitor MA', difficulty: 'intermediate',
    q: 'A "solicitor" municipal advisor is one who:',
    options: ['Provides underwriting services', 'Solicits muni entities to hire other MAs or BDs in exchange for compensation', 'Issues opinions of counsel', 'Provides investment advice to retail investors'],
    correct: 1,
    explanation: 'Solicitor MAs bring in business for other advisors or dealers — compensated for referrals to municipal entities. They have different (lighter) registration and conduct requirements than non-solicitor MAs.',
    nestContext: 'If a firm compensates someone for steering a city to use NEST as arranger, that firm is a solicitor MA. They must register and disclose their compensation. Undisclosed solicitation fees = MSRB enforcement.',
    stepByStep: ['1. Non-solicitor MA: gives advice directly to muni entity', '2. Solicitor MA: paid to steer muni entities to hire others', '3. Both must register as MAs with SEC and MSRB', '4. Solicitor MAs: lighter G-42 requirements, heavier disclosure requirements'],
  },
  {
    id: 45, exam: 'S54', topic: 'Underwriter vs MA', difficulty: 'intermediate',
    q: 'In a negotiated bond offering, the underwriter owes its primary duty to:',
    options: ['The municipal entity issuer', 'The investors purchasing the bonds', 'Itself — it is an arms-length principal', 'FINRA'],
    correct: 2,
    explanation: 'Underwriters are arms-length principals, NOT fiduciaries to the issuer. They serve their own economic interests in the transaction. This is the key distinction from MAs who owe fiduciary duty to the issuer.',
    nestContext: "NEST as arranger/underwriter serves the transaction — we're not Jacaranda Trace's advisor. We structure the deal to place successfully with investors. The borrower should engage an independent MA for advice on deal terms.",
    stepByStep: ['1. MA = fiduciary to issuer (acts in issuer\'s best interest)', '2. Underwriter = arms-length principal (serves its own interest)', '3. This distinction is why you can\'t be both on the same deal', '4. SEC/MSRB: "underwriter carve-out" from MA definition — but not if also giving advice'],
  },
  {
    id: 46, exam: 'S54', topic: 'Political Contributions G-37', difficulty: 'basic',
    q: 'Under MSRB Rule G-37 (applicable to MAs), the ban on business after a prohibited contribution is:',
    options: ['6 months', '1 year', '2 years', 'Permanent'],
    correct: 2,
    explanation: 'G-37 applies to both dealers and MAs: covered contributions trigger a 2-year business ban with that issuer. De minimis: $250/election for officials you can vote for.',
    nestContext: 'NEST maintains a G-37 compliance log. Any contribution over $250 by an MFP or MFPA to any local/state official triggers automatic review. One contribution can cost 2 years of revenue from a major client.',
    stepByStep: ['1. G-37 extended to MAs by MSRB in 2016', '2. Covered person (MFPA) contribution → 2-year ban', '3. De minimis: $250/election if you can vote for that official', '4. Must return any new business obtained in violation'],
  },
  {
    id: 47, exam: 'S54', topic: 'SLGS', difficulty: 'advanced',
    q: 'SLGS (State and Local Government Series) securities are used primarily for:',
    options: ['Investing pension fund assets', 'Escrow accounts for advance refunding of tax-exempt bonds', 'General operating reserves', 'Arbitrage bond portfolios'],
    correct: 1,
    explanation: 'SLGS (pronounced "slugs") are Treasury securities specifically designed for muni bond escrow accounts in advance refundings. They allow precise matching of cash flows while avoiding arbitrage rebate issues.',
    nestContext: "When NEST refunds existing bonds on a deal, SLGS go into the escrow. Bridge Agent tracks SLGS purchase windows (Treasury opens/closes SLGS sales). Post-2017 tax reform limited advance refundings of tax-exempt bonds.",
    stepByStep: ['1. Advance refunding: issue new bonds while old bonds still outstanding', '2. Proceeds go into escrow → invested to pay old bond debt service', '3. SLGS: custom-yield Treasury securities to match escrow cash flows exactly', '4. Prevents arbitrage: SLGS yield matches old bond coupon so no excess yield'],
  },
  {
    id: 48, exam: 'S54', topic: 'Arbitrage Rebate', difficulty: 'advanced',
    q: 'Arbitrage rebate requires issuers to pay to the IRS any earnings on bond proceeds that exceed:',
    options: ['The risk-free rate', 'The bond yield', 'The prime rate', 'The fed funds rate'],
    correct: 1,
    explanation: 'Arbitrage rebate: if you invest tax-exempt bond proceeds and earn more than the bond\'s yield, the excess ("arbitrage") must be paid to the IRS. Prevents issuers from profiting by borrowing tax-exempt and investing at higher taxable rates.',
    nestContext: 'Jacaranda Trace\'s construction fund earns interest during draw period. If the fund earns more than the bond coupon rate, Jacaranda must rebate the excess to IRS within 5 years. Atlas Agent tracks rebate liability.',
    stepByStep: ['1. Tax-exempt bonds allow borrowing at low rates', '2. If proceeds earn > bond yield = "arbitrage" (profiting from tax exemption)', '3. IRS: all arbitrage earnings must be rebated', '4. Exception: 6-month spending exception, 18-month exception for construction bonds'],
  },
  {
    id: 49, exam: 'S54', topic: 'Conduit Financing', difficulty: 'intermediate',
    q: 'In a conduit bond transaction, who files the continuing disclosure agreement (CDA)?',
    options: ['The conduit issuer', 'The obligor/borrower', 'The bond trustee', 'The municipal advisor'],
    correct: 1,
    explanation: 'The obligor (borrower) files the CDA and is responsible for ongoing disclosures. The conduit issuer is the "technical" issuer but has no economic connection — the obligor operates the project and controls the information.',
    nestContext: 'Jacaranda Trace (the CCRC operator) — not the LGFC conduit — signs the CDA and files annual reports + material event notices with EMMA. Bridge Agent manages EMMA filing reminders for all NEST deals.',
    stepByStep: ['1. CDA required: obligor must file annually with EMMA', '2. Conduit issuer (LGFC) has no ongoing obligation', '3. Obligor files: annual financials, DSCR update, occupancy rates', '4. Material events (rating changes, covenant violations) within 10 business days'],
  },
  {
    id: 50, exam: 'S54', topic: 'Form MA', difficulty: 'basic',
    q: 'A municipal advisor must file Form MA (registration) with:',
    options: ['FINRA only', 'MSRB only', 'SEC and MSRB', 'State securities regulator only'],
    correct: 2,
    explanation: 'MAs must register with both the SEC (Form MA filed electronically) and MSRB (G-40 registration). The SEC reviews the form; MSRB collects the regulatory fee and maintains the database.',
    stepByStep: ['1. Dodd-Frank mandated MA registration with SEC', '2. SEC Form MA: filed via EDGAR', '3. Also must register with MSRB (Rule G-40)', '4. Exemptions: banks, swap dealers, underwriters, attorneys giving legal advice'],
    nestContext: 'NEST is NOT registered as an MA. Our placement agent activity doesn\'t require MA registration. Any firm or individual advising issuers on deal terms must check registration requirements with Atticus compliance review.',
  },
  {
    id: 51, exam: 'S54', topic: 'Disclosure', difficulty: 'intermediate',
    q: 'Before entering an advisory engagement, a municipal advisor must disclose to the client:',
    options: ['Only fee information', 'Conflicts of interest and compensation structure', 'Prior enforcement actions only', 'Nothing unless client asks'],
    correct: 1,
    explanation: 'G-42 requires MAs to disclose: (1) all conflicts of interest, (2) compensation arrangements (including payments from third parties), and (3) any potential adverse interests. Must be disclosed in writing before advice begins.',
    nestContext: 'If NEST ever takes an MA engagement, the engagement letter must disclose: NEST\'s fee, any payments from lenders/counterparties, relationships with Hylant (surety partner), and any competitive advisory interests.',
    stepByStep: ['1. Written disclosure before engagement begins', '2. Must disclose: ALL conflicts of interest', '3. Must disclose: compensation structure (fixed, success, ongoing)', '4. Must disclose: third-party payments that could influence advice'],
  },
  {
    id: 52, exam: 'S54', topic: 'Exempt from MA Registration', difficulty: 'intermediate',
    q: 'Which of the following is specifically EXEMPT from municipal advisor registration?',
    options: ['Registered investment advisors giving advice to muni entities', 'Underwriters advising on the structure of their own underwritten deal', 'Third-party advisors paid by underwriters', 'All financial consultants'],
    correct: 1,
    explanation: 'Underwriters are exempt from MA registration when advising on their own underwriting deals — the "underwriter exemption." However, if they give advice outside their underwriting role, the exemption may not apply.',
    nestContext: 'NEST\'s structuring advice to borrowers falls under the underwriter exemption. We\'re arranging the transaction, not providing independent MA advice. The line blurs when an arranger gives investment advice on escrowed proceeds.',
    stepByStep: ['1. Underwriter exemption: excludes underwriters advising on their own deal', '2. Also exempt: bank municipal advisors, swap dealers, attorneys (legal advice only)', '3. NOT exempt: RIAs giving muni advice, financial consultants paid by the issuer', '4. Dual-hat risk: underwriter who also gives "MA-like" advice loses exemption'],
  },
  {
    id: 53, exam: 'S54', topic: 'Best Interest Standard', difficulty: 'advanced',
    q: 'The municipal advisor best interest standard requires:',
    options: ['Always recommending the lowest-cost option', 'Placing the municipal entity\'s interest above the MA\'s own monetary interest', 'Recommending only investment-grade securities', 'Deferring to the issuer\'s own preferences always'],
    correct: 1,
    explanation: 'The MA best interest standard (G-42): MA must place the interests of the municipal entity above its own. This is not a "suitability" standard — it\'s closer to an investment advisor\'s fiduciary standard.',
    nestContext: 'An MA advising Jacaranda Trace cannot recommend a higher-fee bond structure just to earn more. They must recommend what\'s best for Jacaranda — even if it means lower advisory fees. This is why underwriters and MAs are separate roles.',
    stepByStep: ['1. Best interest = client first, always', '2. Cannot recommend higher-cost structure to earn more fees', '3. Must disclose if any recommendation benefits the MA financially', '4. Higher standard than broker-dealer suitability (which allows self-interest if disclosed)'],
  },
  {
    id: 54, exam: 'S54', topic: 'Written Supervisory Procedures', difficulty: 'intermediate',
    q: 'A municipal advisor firm must establish written supervisory procedures (WSPs) to:',
    options: ['Only cover trading activities', 'Achieve compliance with all MSRB rules applicable to the MA', 'Replace FINRA oversight', 'Be filed with SEC quarterly'],
    correct: 1,
    explanation: 'MSRB Rule G-44 requires MA firms to establish and enforce WSPs reasonably designed to ensure compliance with all applicable MSRB rules. Must designate supervisors and review procedures regularly.',
    nestContext: "When NEST establishes its BD under Britehorn's sponsorship, Atticus Agent drafts the full WSP package — one set for broker-dealer activity (FINRA 3110), another for any MA activity (MSRB G-44). Separate regulatory frameworks.",
    stepByStep: ['1. G-44 = supervisory requirement for MA firms', '2. WSPs must cover all MSRB rules applicable to the firm\'s business', '3. Must designate principal supervisors for each business line', '4. Annual review and update of WSPs required'],
  },
  {
    id: 55, exam: 'S54', topic: 'Investment of Proceeds', difficulty: 'advanced',
    q: 'A municipal entity hires a firm to advise on investing bond proceeds. This firm must be registered as:',
    options: ['A broker-dealer only', 'An investment advisor only', 'A municipal advisor', 'Either a broker-dealer or investment advisor, not an MA'],
    correct: 2,
    explanation: 'Advising a municipal entity on how to invest bond proceeds IS municipal advisory activity — requires MA registration. This catches many RIAs and banks that advise on muni investment portfolios without realizing they need MA registration.',
    nestContext: 'Atlas Agent (NEST\'s modeling engine) helps optimize Jacaranda\'s construction fund investment. This function must be performed by or supervised by a registered MA. Key compliance checkpoint for NEST as we expand services.',
    stepByStep: ['1. MA definition: advice to muni entity about ISSUANCE or INVESTMENT of proceeds', '2. Investment advice on bond proceeds = MA activity', '3. Even an SEC-registered RIA needs separate MA registration for this', '4. Banks, swap dealers: separate exemptions but narrow — check carefully'],
  },
  {
    id: 56, exam: 'S54', topic: 'EMMA', difficulty: 'basic',
    q: 'EMMA (Electronic Municipal Market Access) is operated by:',
    options: ['SEC', 'FINRA', 'MSRB', 'Treasury'],
    correct: 2,
    explanation: 'EMMA is operated by the MSRB — it\'s the official repository for muni bond disclosures, trade data, and official documents. Free public access. All 15c2-12 continuing disclosures must be filed here.',
    nestContext: 'NEST monitors EMMA for all portfolio deals. When a covenant is breached, the material event notice appears on EMMA within 10 business days. Bridge Agent scrapes EMMA daily for filings on NEST-managed bonds.',
    stepByStep: ['1. EMMA = Electronic Municipal Market Access', '2. Operated by MSRB, publicly accessible at emma.msrb.org', '3. Contains: official statements, continuing disclosures, trade data', '4. Required filing destination under SEC Rule 15c2-12'],
  },
  {
    id: 57, exam: 'S54', topic: 'Timing of Registration', difficulty: 'intermediate',
    q: 'A person acting as a municipal advisor must register:',
    options: ['Within 30 days of acting', 'Before providing any municipal advisory services', 'Only if paid more than $100,000', 'After completing the S54 exam'],
    correct: 1,
    explanation: 'MA registration must be completed BEFORE providing any municipal advisory services. Acting as unregistered MA is a violation of Dodd-Frank — no grace period.',
    nestContext: 'Before NEST adds any formal MA services (advising on bond structure for borrowers), Atticus Agent must verify MA registration is in place. Operating without registration risks SEC enforcement and disgorgement of all fees earned.',
    stepByStep: ['1. No grace period for MA registration', '2. Must register before providing FIRST piece of advice', '3. SEC has brought enforcement against unregistered MAs', '4. Registration: Form MA with SEC + G-40 filing with MSRB'],
  },
  {
    id: 58, exam: 'S54', topic: 'Record Keeping', difficulty: 'basic',
    q: 'Municipal advisors must retain records of client engagements for a minimum of:',
    options: ['2 years', '3 years', '5 years', '7 years'],
    correct: 2,
    explanation: 'MSRB Rule G-9 requires MAs to maintain books and records for at least 5 years, with the first 2 years in an easily accessible place. Similar to broker-dealer record retention requirements.',
    nestContext: 'NEST data architecture includes a 7-year retention policy for all deal documents (exceeding the 5-year minimum). This protects against regulatory inquiries and supports LGFC audit requirements on conduit bonds.',
    stepByStep: ['1. G-9 = records retention for MAs', '2. Minimum 5-year retention', '3. First 2 years: must be immediately accessible (not archived)', '4. Records include: engagement letters, advice given, conflicts disclosed'],
  },
  {
    id: 59, exam: 'S54', topic: 'Prohibited Conduct', difficulty: 'intermediate',
    q: 'Which of the following is prohibited conduct for a municipal advisor under MSRB rules?',
    options: ['Charging success fees', 'Accepting undisclosed compensation from third parties', 'Advising on negotiated bond sales', 'Using EMMA for research'],
    correct: 1,
    explanation: 'Undisclosed third-party compensation is a core prohibition for MAs. If a lender or dealer pays an MA to steer clients their way, it MUST be disclosed — or it violates G-42\'s duty of loyalty.',
    nestContext: 'If Hylant (NEST\'s surety partner) paid a fee to someone who then recommended Hylant\'s surety to a muni client, that person (if an MA) must disclose this relationship. Undisclosed = conflict = potential fraud.',
    stepByStep: ['1. G-42 prohibits undisclosed conflicts — especially hidden compensation', '2. Third-party payments: lenders, placement agents, attorneys paying MAs', '3. Must disclose: the source, amount, and nature of all compensation', '4. Failure to disclose = violation of duty of loyalty = enforcement risk'],
  },
  {
    id: 60, exam: 'S54', topic: 'Applicable Rules', difficulty: 'basic',
    q: 'Which regulatory body primarily oversees municipal advisors\' conduct rules?',
    options: ['FINRA', 'SEC only', 'MSRB', 'OCC'],
    correct: 2,
    explanation: 'The MSRB writes the conduct rules for municipal advisors (G-40 series). The SEC registers MAs and has enforcement authority. FINRA has no jurisdiction over MAs — they are not broker-dealers.',
    nestContext: 'NEST compliance tracks two regulatory frameworks: FINRA rules (for BD activities) and MSRB rules (for any MA activities). Atticus Agent maintains a dual-framework compliance calendar — separate filing dates, separate rule updates.',
    stepByStep: ['1. MSRB: writes conduct rules for MAs (and BDs in muni space)', '2. SEC: registers MAs, enforcement authority', '3. FINRA: NO jurisdiction over MA activities', '4. State securities regulators: some registration requirements for MAs'],
  },

  // ─── SERIES 28 — Introducing Broker-Dealer Financial/Operations (20 questions) ───
  {
    id: 61, exam: 'S28', topic: 'Net Capital', difficulty: 'intermediate',
    q: 'Under SEC Rule 15c3-1, the minimum net capital for an introducing broker-dealer is:',
    options: ['$5,000', '$50,000', '$250,000', '$1,000,000'],
    correct: 1,
    explanation: 'An introducing BD (no customer funds) minimum net capital = $50,000 under the aggregate indebtedness standard (AI/NC ≤ 15:1), OR $5,000 under the alternative method. Most introducing BDs use $50,000 minimum.',
    nestContext: "When NEST establishes its BD subsidiary under Britehorn's sponsorship, achieving and maintaining $50,000 minimum net capital is the foundational regulatory requirement. Net capital must be calculated daily.",
    stepByStep: ['1. Rule 15c3-1 = net capital rule for broker-dealers', '2. Introducing BD: doesn\'t hold customer funds or securities', '3. Aggregate indebtedness standard: AI/NC ≤ 15:1, minimum $50,000', '4. Alternative standard: NC ≥ 2% of aggregate debit items, minimum $250,000'],
    formulaUsed: 'Aggregate Indebtedness / Net Capital ≤ 15:1',
  },
  {
    id: 62, exam: 'S28', topic: 'Net Capital', difficulty: 'advanced',
    q: 'Net capital is calculated as:',
    options: ['Total assets minus total liabilities', 'Net worth minus non-allowable assets plus/minus haircuts', 'Revenue minus expenses', 'Stockholders equity only'],
    correct: 1,
    explanation: 'Net Capital = Net Worth − Non-allowable assets (illiquid assets, assets subject to liens) ± haircuts on securities positions. Haircuts reduce the value of securities positions to reflect market risk.',
    nestContext: 'NEST BD will hold positions in muni bonds as inventory. A $10M muni bond position takes a 9% haircut ($900k deducted from net capital). High-yield positions take larger haircuts (15-30%). Haircut management is critical.',
    stepByStep: ['1. Start with stockholders equity (net worth)', '2. Subtract non-allowable assets (investments in subs, illiquid assets, fixed assets)', '3. Apply haircuts: deduct % of securities positions (varies by type)', '4. Result: Net Capital — must exceed minimums daily'],
  },
  {
    id: 63, exam: 'S28', topic: 'SIPC', difficulty: 'basic',
    q: 'SIPC protection covers customer accounts up to:',
    options: ['$250,000 total', '$250,000 cash + $250,000 securities', '$500,000 total with $250,000 cash sublimit', '$1,000,000 total'],
    correct: 2,
    explanation: 'SIPC covers up to $500,000 per separate customer, with a $250,000 sublimit for cash. Securities positions can be covered up to $500,000 total. SIPC does NOT cover investment losses — only missing/stolen assets.',
    nestContext: 'NEST\'s institutional QIB clients have accounts far exceeding SIPC limits. They rely on the BD\'s financial strength (net capital) and clearinghouse protections, not SIPC. SIPC is primarily a retail protection mechanism.',
    stepByStep: ['1. SIPC = Securities Investor Protection Corporation', '2. Coverage: $500,000 per separate customer', '3. Cash sublimit: $250,000 maximum cash protection', '4. NOT insurance: doesn\'t cover market losses, only missing assets from BD failure'],
  },
  {
    id: 64, exam: 'S28', topic: 'Customer Protection', difficulty: 'advanced',
    q: 'SEC Rule 15c3-3 (Customer Protection Rule) requires BDs to:',
    options: ['Maintain minimum net capital', 'Segregate customer cash and fully paid securities', 'File monthly financial reports', 'Obtain customer suitability profiles'],
    correct: 1,
    description: 'Rule 15c3-3: BDs must segregate customer funds (in "special reserve bank account") and maintain physical possession/control of fully paid customer securities. Prevents customer assets from being used to fund firm operations.',
    explanation: '15c3-3 = Customer Protection Rule: customer cash must go into a separate reserve bank account; customer fully-paid securities must be in the firm\'s possession/control. Cannot co-mingle with firm assets.',
    nestContext: 'Introducing BDs that clear through another firm (prime broker) have a simplified 15c3-3 regime — the clearing firm handles segregation. This is why introducing BDs have lower capital requirements.',
    stepByStep: ['1. 15c3-3 = protects customer assets at broker-dealers', '2. Cash: must be in special reserve bank account (formula-based)', '3. Fully-paid securities: must be in firm\'s possession/control (not rehypothecated)', '4. Introducing BDs: clearing firm handles this — simpler compliance'],
  },
  {
    id: 65, exam: 'S28', topic: 'FOCUS Report', difficulty: 'basic',
    q: 'The FOCUS (Financial and Operational Combined Uniform Single) report is filed:',
    options: ['Daily', 'Monthly (for most BDs)', 'Quarterly only', 'Annually only'],
    correct: 1,
    explanation: 'Most broker-dealers file FOCUS reports monthly. BDs with less than $250,000 in assets may file quarterly. The FOCUS report provides FINRA with financial and operational data to monitor BD health.',
    nestContext: 'NEST\'s BD (when established) must file FOCUS monthly. Atticus Agent maintains a FOCUS filing calendar. A missed FOCUS filing triggers immediate FINRA inquiry — critical compliance deadline.',
    stepByStep: ['1. FOCUS = Financial and Operational Combined Uniform Single report', '2. Filed with FINRA (via WebCRD/eFOCUS system)', '3. Most BDs: monthly by the 17th of following month', '4. Smaller BDs (<$250k assets): quarterly filing permitted'],
  },
  {
    id: 66, exam: 'S28', topic: 'Books and Records', difficulty: 'intermediate',
    q: 'Under SEC Rule 17a-3, broker-dealers must maintain customer account records for at least:',
    options: ['2 years', '3 years', '6 years', '10 years'],
    correct: 2,
    explanation: 'Rule 17a-3 (books and records): customer account records must be maintained for 6 years. General ledger and partnership/articles records: 3 years minimum (but 6 years is industry standard practice).',
    nestContext: 'NEST documents all deal files for 7 years (exceeds regulatory minimum). This covers potential regulatory inquiries, litigation, and LGFC audit requirements. Atlas Agent archives all deal models and correspondence.',
    stepByStep: ['1. 17a-3: prescribes WHAT records BDs must keep', '2. 17a-4: prescribes HOW LONG records must be kept', '3. Customer account records: 6-year minimum', '4. First 2 years: must be immediately accessible (not archived)'],
  },
  {
    id: 67, exam: 'S28', topic: 'Haircuts', difficulty: 'advanced',
    q: 'The haircut on U.S. Treasury securities under Rule 15c3-1 is approximately:',
    options: ['0%', '0.5 to 6%', '9%', '25%'],
    correct: 1,
    explanation: 'Treasury securities have low haircuts: 0-6% depending on maturity. Short-term Treasuries (under 3 months): 0%. Long-term Treasuries (>25 years): 6%. Munis and corporates have higher haircuts.',
    nestContext: 'NEST BD holding $50M in muni bonds takes a 9% haircut = $4.5M deducted from net capital. Treasury bills would only take a 0.5% haircut. Bond inventory composition dramatically affects net capital position.',
    stepByStep: ['1. Haircut = discount applied to securities for net capital calculation', '2. Reflects liquidation risk (can you sell quickly at par?)', '3. Treasuries (< 3mo): 0%; Treasuries (> 25yr): 6%', '4. Munis: 9-15% depending on maturity; Corporates: 15-30%'],
  },
  {
    id: 68, exam: 'S28', topic: 'Net Capital Computation', difficulty: 'intermediate',
    q: 'If aggregate indebtedness is $600,000 and net capital is $50,000, the firm is:',
    options: ['In compliance (12:1 ratio)', 'In violation (15:1 limit exceeded)', 'In compliance (must check alternative method)', 'In violation (minimum $250,000 required)'],
    correct: 0,
    explanation: 'AI/NC = $600k/$50k = 12:1, which is BELOW the 15:1 limit. The firm is in compliance. Also meets $50,000 minimum. Note: at 15:1 exactly, the firm is at the limit and any increase in liabilities causes a violation.',
    nestContext: 'NEST BD must compute net capital daily. At 12:1, there\'s only a $150k buffer before hitting the 15:1 limit. A $150k increase in aggregate indebtedness (one more payable) would trigger a violation.',
    stepByStep: ['1. AI/NC ratio = $600,000 / $50,000 = 12:1', '2. Limit: 15:1 maximum', '3. 12:1 < 15:1 → IN COMPLIANCE', '4. But the buffer is thin — only $150k before violation'],
    formulaUsed: 'AI/NC Ratio = Aggregate Indebtedness / Net Capital',
  },
  {
    id: 69, exam: 'S28', topic: 'Early Warning', difficulty: 'advanced',
    q: 'An "early warning" notification to FINRA is required when net capital falls below:',
    options: ['120% of the minimum', '150% of the minimum', '200% of the minimum', '110% of the minimum'],
    correct: 1,
    explanation: 'Early warning: broker-dealers must notify FINRA when net capital falls below 120% of the minimum. This gives FINRA advance notice before the firm actually violates minimum requirements.',
    nestContext: "NEST BD will set internal alarm at 130% of minimum (buffer above the 120% early warning). Atticus Agent monitors daily net capital computation. A breach triggers automatic escalation to NEST's Chief Compliance Officer.",
    stepByStep: ['1. Minimum net capital = say $50,000 for introducing BD', '2. 120% of minimum = $60,000', '3. If net capital falls to $60,000 → must notify FINRA within 24 hours', '4. At minimum ($50k): full violation — must stop taking new business'],
  },
  {
    id: 70, exam: 'S28', topic: 'Segregation', difficulty: 'intermediate',
    q: 'Hypothecation of customer securities means:',
    options: ['Customer securities held in Street name', 'Pledging customer securities as collateral for BD\'s own loans', 'Moving securities between accounts', 'Reporting customer securities to SIPC'],
    correct: 1,
    explanation: 'Hypothecation = pledging customer securities as collateral for broker-dealer\'s own borrowings. Rule 8c-1 limits hypothecation to 140% of aggregate debit balances of all customers. No hypothecation of fully-paid securities.',
    nestContext: 'NEST\'s clearing firm can hypothecate margin account securities (up to 140% of debit balances). Fully-paid securities (in cash accounts) cannot be hypothecated. This is a core 15c3-3 protection.',
    stepByStep: ['1. Hypothecation = pledging securities as loan collateral', '2. BDs can hypothecate margin account securities to fund their lending', '3. Limit: 140% of aggregate customer debit balances', '4. Fully-paid and excess margin securities: CANNOT be hypothecated (15c3-3)'],
  },
  {
    id: 71, exam: 'S28', topic: 'Aggregate Indebtedness', difficulty: 'intermediate',
    q: 'Which of the following is included in aggregate indebtedness for Rule 15c3-1?',
    options: ['Amounts owed to customers', 'Liabilities to non-customers only', 'All balance sheet liabilities', 'Net capital only'],
    correct: 0,
    explanation: 'Aggregate indebtedness (AI) includes ALL liabilities except: subordinated borrowings, certain deferrable items, and deferred tax liabilities. Primarily: amounts owed to customers, bank loans, and accounts payable.',
    nestContext: 'NEST BD must carefully classify liabilities when computing AI. Subordinated loans from Sean\'s capital contribution can be excluded from AI (with proper subordination agreement) — boosting the AI/NC ratio calculation.',
    stepByStep: ['1. AI = total liabilities minus specific exclusions', '2. Included: amounts owed customers, bank payables, accrued liabilities', '3. Excluded: properly subordinated borrowings, deferred taxes', '4. Goal: keep AI low to maintain favorable AI/NC ratio'],
  },
  {
    id: 72, exam: 'S28', topic: 'Reserve Formula', difficulty: 'advanced',
    q: 'Under Rule 15c3-3, the customer reserve formula requires deposits when:',
    options: ['Credits exceed debits', 'Debits exceed credits', 'Total customer assets exceed $1M', 'Any new customer account is opened'],
    correct: 0,
    explanation: 'Reserve formula: if customer credits (what firm owes customers) exceed customer debits (what customers owe firm), the excess must be deposited in the special reserve bank account by the following Monday.',
    nestContext: 'For introducing BDs clearing through a prime broker, the clearing firm handles the 15c3-3 reserve computation. NEST\'s BD structure will leverage a prime broker to avoid direct reserve computation complexity.',
    stepByStep: ['1. Credits: customer free credit balances, short sale proceeds held for customers', '2. Debits: margin loans to customers, amounts for securities purchased not yet paid', '3. If Credits > Debits → excess must go into reserve bank account', '4. Computed weekly, deposited by Monday following computation date'],
    formulaUsed: 'Reserve Required = Credits − Debits (if positive)',
  },
  {
    id: 73, exam: 'S28', topic: 'Subordinated Borrowings', difficulty: 'advanced',
    q: 'A subordinated loan may be included as capital in net capital computation if:',
    options: ['It is payable on demand', 'It meets SEC Rule 15c3-1 subordination agreement requirements', 'It is from a bank', 'It is less than 1 year in maturity'],
    correct: 1,
    explanation: 'Subordinated borrowings can be counted as capital (reducing AI) if the subordination agreement meets exact SEC requirements: minimum maturity, FINRA approval, proper subordination language, no withdrawal without FINRA consent.',
    nestContext: "Sean's equity contributions to NEST BD are classified as equity (capital), not debt. If a third-party provides subordinated debt capital, the Subordination Agreement must be reviewed by NEST's securities counsel before execution.",
    stepByStep: ['1. Sub loans are EXCLUDED from aggregate indebtedness if properly structured', '2. Must meet SEC Rule 15c3-1, Appendix D requirements', '3. FINRA must approve large subordinated borrowings', '4. Cannot be withdrawn if BD is in capital violation'],
  },
  {
    id: 74, exam: 'S28', topic: 'Annual Audit', difficulty: 'basic',
    q: 'Broker-dealers are required to file audited financial statements with regulators:',
    options: ['Monthly', 'Quarterly', 'Annually', 'Only upon request'],
    correct: 2,
    explanation: 'All BDs must have annual audits by an independent PCAOB-registered public accountant, filed with FINRA within 60 days of fiscal year end. The audit must include a net capital computation.',
    nestContext: 'NEST BD annual audit will be filed by March 31 (if calendar year-end). Selecting a PCAOB-registered auditor with muni/BD experience is critical. Atticus Agent tracks audit deadlines and manages auditor relationship.',
    stepByStep: ['1. Annual audit required: PCAOB-registered accountant', '2. Must audit: financial statements + net capital computation + 15c3-3', '3. Filing: with SEC and FINRA within 60 days of fiscal year-end', '4. Qualified opinion or adverse opinion → FINRA notification required'],
  },
  {
    id: 75, exam: 'S28', topic: 'Risk Assessment', difficulty: 'intermediate',
    q: 'Under SEC Rule 17h-1T, broker-dealers must file risk assessment reports if:',
    options: ['They have more than $100M in assets', 'They are affiliates of entities with significant non-securities activities', 'They execute more than 1,000 trades per day', 'They have more than 50 registered representatives'],
    correct: 1,
    explanation: '17h-1T: BDs that are affiliates of holding companies with significant non-securities activities must file risk assessment reports. Helps SEC understand the BD\'s exposure to its affiliates\' risks.',
    nestContext: 'NEST BD as a subsidiary of Arden Edge Capital may need to assess 17h-1T filing requirements. If Arden Edge has significant non-securities operations (real estate, fund management), the risk assessment filing may apply.',
    stepByStep: ['1. 17h-1T = risk assessment for BDs with large affiliates', '2. Triggered: BD\'s affiliate has >$200M in non-securities assets', '3. Report: filed quarterly with SEC', '4. Discloses: affiliate financial condition, agreements between BD and affiliates'],
  },
  {
    id: 76, exam: 'S28', topic: 'Net Capital Events', difficulty: 'intermediate',
    q: 'When a BD\'s net capital falls below the minimum required, it must:',
    options: ['File a FOCUS report immediately', 'Cease opening new accounts and immediately notify regulators', 'Obtain approval from FINRA to continue operating', 'Increase liabilities to restore balance'],
    correct: 1,
    explanation: 'Net capital violation: must immediately cease business and notify SEC, FINRA, and relevant SRO. Cannot accept new customer accounts, orders, or securities. Notify within 24 hours of discovering the violation.',
    nestContext: 'A net capital violation for NEST BD would trigger an immediate operational freeze. Atticus Agent has an automated alert at 115% of minimum (well above the violation level) to prevent this from ever occurring.',
    stepByStep: ['1. Discover net capital violation → immediate notification to SEC/FINRA', '2. Cease: accepting new accounts, accepting new orders, soliciting business', '3. Existing business: may wind down but cannot take new positions', '4. Restore capital or liquidate — cannot resume normal operations until cured'],
  },
  {
    id: 77, exam: 'S28', topic: 'Possession and Control', difficulty: 'advanced',
    q: 'Under Rule 15c3-3, "possession and control" of customer securities requires them to be:',
    options: ['In the customer\'s own brokerage account only', 'In the BD\'s possession or in a specified "good control location"', 'Reported to SIPC monthly', 'Held by an independent custodian only'],
    correct: 1,
    explanation: 'Good control locations include: DTCC/DTC, bank satisfactory to SEC, another BD (under proper clearing agreement), or the firm\'s own vault. Locations that don\'t qualify include: collateral pledged to lenders, affiliate custody.',
    nestContext: 'NEST BD uses DTC as the primary settlement and custody location — all securities positions maintained through DTC qualify as good control locations. This simplifies 15c3-3 compliance dramatically.',
    stepByStep: ['1. Good control location: DTC (most common), DTCC, qualified bank', '2. NOT a good control location: pledged securities, affiliate custody, unqualified custodians', '3. BDs must reconcile possession/control daily', '4. Shortfall in good control → must cure within one business day'],
  },
  {
    id: 78, exam: 'S28', topic: 'Trade Confirmation', difficulty: 'basic',
    q: 'A trade confirmation must be sent to customers no later than:',
    options: ['Same business day as trade', 'Completion of the transaction (settlement)', 'Within 24 hours', 'T+2'],
    correct: 1,
    explanation: 'Rule 10b-10 requires confirmation delivery no later than "completion of the transaction" — generally at or before settlement (T+2). Must include: security description, price, commission/markup, and capacity (agent vs. principal).',
    nestContext: 'NEST bond desk confirmations must specify if we acted as agent (commission) or principal (markup/markdown). QIB clients receive electronic confirmations — DTC\'s systems generate confirms automatically through the NSCC.',
    stepByStep: ['1. Rule 10b-10: confirmation delivery requirements', '2. Must be sent: at or before completion (settlement = T+2)', '3. Contents: security, price, date, quantity, commission or markup, BD capacity', '4. Electronic confirmation acceptable with customer consent'],
  },
  {
    id: 79, exam: 'S28', topic: 'Anti-Money Laundering', difficulty: 'intermediate',
    q: 'A broker-dealer\'s AML program must include:',
    options: ['Daily cash transaction reports only', 'Customer identification procedures, suspicious activity monitoring, and employee training', 'Reporting all trades to FinCEN', 'Annual review by FINRA'],
    correct: 1,
    explanation: 'FINRA Rule 3310 AML program: must include (1) policies to detect/prevent money laundering, (2) customer identification program (CIP), (3) suspicious activity monitoring and SAR filing, (4) annual independent testing, (5) employee training.',
    nestContext: 'NEST BD requires AML procedures for all new accounts. QIB onboarding includes CIP verification (EIN, ownership structure, beneficial owners for entities with >25% ownership). Atticus Agent maintains AML compliance calendar.',
    stepByStep: ['1. AML four pillars: policies, CIP, monitoring, training', '2. CIP: verify identity of all new account holders (Rule 31 CFR 1023.220)', '3. SAR filing: suspicious activity > $5,000 within 30 days', '4. Annual independent testing of AML program required'],
  },
  {
    id: 80, exam: 'S28', topic: 'Net Capital Computation', difficulty: 'advanced',
    q: 'A BD has: net worth $500k, non-allowable assets $150k, haircuts on securities $80k. Net capital is:',
    options: ['$500,000', '$350,000', '$270,000', '$430,000'],
    correct: 2,
    explanation: 'Net Capital = Net Worth − Non-allowable assets − Haircuts = $500k − $150k − $80k = $270,000.',
    nestContext: 'NEST BD daily net capital computation: start with equity, subtract fixed/illiquid assets (non-allowable), subtract position haircuts. The remaining $270k must exceed the $50k minimum and maintain the 15:1 AI/NC ratio.',
    stepByStep: [
      '1. Start: Net Worth = $500,000',
      '2. Minus non-allowable assets: $500,000 − $150,000 = $350,000',
      '3. Minus securities haircuts: $350,000 − $80,000 = $270,000',
      '4. Net Capital = $270,000 (must exceed minimum and maintain ratios)',
    ],
    formulaUsed: 'Net Capital = Net Worth − Non-Allowable Assets − Haircuts on Securities',
  },
];

export interface DayPlan {
  day: number;
  topic: string;
  xp: number;
  questionIds: number[];
  keyFormula?: string;
  labEngine?: string;
}

export interface WeekPlan {
  week: number;
  title: string;
  exam: 'S7' | 'S52' | 'S54' | 'S28';
  focus: string;
  xpTarget: number;
  badge: string;
  days: DayPlan[];
  weeklyQuizCount: number;
}

export const FOUR_WEEK_PLAN: WeekPlan[] = [
  {
    week: 1, title: 'Municipal Foundations', exam: 'S52',
    focus: 'GO vs Revenue bonds, TEFRA, MSRB rules, yield math',
    xpTarget: 500, badge: 'MuniFoundations', weeklyQuizCount: 20,
    days: [
      { day: 1, topic: 'GO vs Revenue Bonds', xp: 100, questionIds: [1, 8, 9, 16], keyFormula: 'DSCR = NOI / Annual Debt Service', labEngine: 'DSCR Engine' },
      { day: 2, topic: 'TEFRA & Volume Cap', xp: 100, questionIds: [2, 13, 47, 48], keyFormula: 'PAB Volume Cap ≈ $110 per capita' },
      { day: 3, topic: 'MSRB Core Rules G-17 / G-30 / G-37', xp: 100, questionIds: [5, 6, 14, 12], keyFormula: 'G-37: $250 de minimis, 2-year ban' },
      { day: 4, topic: 'Yield Calculations & Tax Equivalency', xp: 150, questionIds: [3, 4, 7, 20], keyFormula: 'TEY = Muni Yield / (1 − Tax Rate)', labEngine: 'DSCR Engine' },
      { day: 5, topic: 'S52 Conduit, Credit & Disclosure', xp: 200, questionIds: [10, 11, 17, 18, 19], keyFormula: 'Current Yield = Annual Coupon / Market Price' },
    ],
  },
  {
    week: 2, title: 'Bond Math Mastery', exam: 'S7',
    focus: 'YTM, Duration, Convexity, Options fundamentals',
    xpTarget: 750, badge: 'BondMath', weeklyQuizCount: 20,
    days: [
      { day: 1, topic: 'Price / Yield Relationship', xp: 100, questionIds: [21, 22, 31, 33], keyFormula: 'P = Σ(C/(1+y)^t) + F/(1+y)^n', labEngine: 'DSCR Engine' },
      { day: 2, topic: 'Duration & Convexity', xp: 150, questionIds: [23, 24], keyFormula: '% ΔP ≈ −Modified Duration × Δy', labEngine: 'SHAP Suite' },
      { day: 3, topic: 'Options: Calls, Puts, Strategies', xp: 150, questionIds: [25, 26, 27, 28, 38], keyFormula: 'Call BEP = Strike + Premium; Put BEP = Strike − Premium' },
      { day: 4, topic: 'Margin, Short Sales & Market Mechanics', xp: 100, questionIds: [30, 32, 35, 39], keyFormula: 'Initial Margin = 50% × Purchase Price' },
      { day: 5, topic: 'S7 Comprehensive Review', xp: 250, questionIds: [29, 34, 36, 37, 40], keyFormula: 'NAV = (Assets − Liabilities) / Shares Outstanding' },
    ],
  },
  {
    week: 3, title: 'Municipal Advisor Framework', exam: 'S54',
    focus: 'Fiduciary duty, G-42, registration, EMMA, arbitrage',
    xpTarget: 1000, badge: 'MuniAdvisor', weeklyQuizCount: 20,
    days: [
      { day: 1, topic: 'MA Registration & Form MA', xp: 100, questionIds: [41, 50, 57], keyFormula: 'Register with SEC + MSRB before providing ANY advice' },
      { day: 2, topic: 'Fiduciary Duty & G-42', xp: 150, questionIds: [42, 43, 53, 59], keyFormula: 'Best Interest = Client First, Always' },
      { day: 3, topic: 'MA vs Underwriter + Solicitors', xp: 100, questionIds: [44, 45, 52], keyFormula: 'Underwriter = arms-length principal; MA = fiduciary' },
      { day: 4, topic: 'G-37, Disclosures & EMMA', xp: 150, questionIds: [46, 51, 54, 56, 60], keyFormula: 'G-37: 2-year ban after $250+ contribution' },
      { day: 5, topic: 'SLGS, Arbitrage & Conduit', xp: 500, questionIds: [47, 48, 49, 55, 58], keyFormula: 'Arbitrage Rebate: earnings > bond yield → pay IRS', labEngine: 'TEFRA Engine' },
    ],
  },
  {
    week: 4, title: 'BD Operations & Capital', exam: 'S28',
    focus: 'Net capital, customer protection, FOCUS reports, AML',
    xpTarget: 1500, badge: 'OpsExpert', weeklyQuizCount: 20,
    days: [
      { day: 1, topic: 'Net Capital Rule 15c3-1', xp: 150, questionIds: [61, 62, 67, 68, 80], keyFormula: 'Net Capital = Net Worth − Non-Allowable − Haircuts' },
      { day: 2, topic: 'Customer Protection 15c3-3', xp: 150, questionIds: [64, 70, 72, 77], keyFormula: 'Reserve = Credits − Debits (if positive)' },
      { day: 3, topic: 'SIPC, AML & Suitability', xp: 150, questionIds: [63, 71, 75, 79], keyFormula: 'SIPC: $500k total / $250k cash sublimit' },
      { day: 4, topic: 'FOCUS Reports & Books/Records', xp: 150, questionIds: [65, 66, 74, 78], keyFormula: 'FOCUS: monthly by the 17th' },
      { day: 5, topic: 'Capital Events & Final Drill', xp: 900, questionIds: [69, 73, 76, 71, 72], keyFormula: 'Early Warning: NC < 120% of minimum → notify FINRA' },
    ],
  },
];
